{{- if .Values.private }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipfs-cluster-init
subjects:
  - kind: ServiceAccount
    name: ipfs-private-cluster-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ipfs-private-cluster-init
{{- end }}
